### ISSUE TITLE
nvidia card remains ON after stopping primusrun

### ISSUE THREAD

**Issue by nikonikolov** [WhiteWolf1776/Bumblebee-SlackBuilds#13]
When I start an application with primusrun and then close it, the nvidia card remains ON. This is evident from the shortened battery life and from the fact that `cat /proc/acpi/bbswitch` prints `ON`. Tried manually unloading the nvidia module but even with `--force` option the system does not allow me and says it's in use. I also tried using `bbswitch` but bash says that this command is not found, although I installed the package. What configurations should I perform to make the nvidia card switch off automatically after the process that uses primusrun is terminated? I am using the proprietary nvidia drivers.

**Comment by ryanpcmcquen** [comment]
Have you tried the recommended way of turning off `bbswitch`?

https://github.com/Bumblebee-Project/bbswitch#turn-the-card-off-respectively-on

**Comment by nikonikolov** [comment]
yes. after the tee command the `cat /proc/acpi/bbswitch` still prints `0000:01:00.0 ON`. Actually I just found out that the nvidia card starts when bumblebeed is started, no need to run primusrun to turn it on. Isn't there an automated way that will switch it on only when primusrun is using it?

**Comment by nikonikolov** [comment]
Sorry, my mistake, one of the nvidia modules was still loaded so that's why it could not switch off. Anyway, how can I automate the behaviour?

**Comment by ryanpcmcquen** [comment]
Writing a shell wrapper for `primusrun` that turns on the card would be somewhere to start ... glad to hear your other issue was fixed!

**Comment by nikonikolov** [comment]
Thanks. Just a final question https://github.com/Bumblebee-Project/bbswitch#enable-card-on-shutdown - I am struggling to find out which will be the equivalent path for this file on Slackware?

**Comment by ryanpcmcquen** [comment]
@nikonikolov, I'm not sure, try this command:

```sh
find /etc -name bbswitch.conf
```
