### ISSUE TITLE
download link from nvidia.com is not valid

### ISSUE THREAD

**Issue by mashomee** [WhiteWolf1776/Bumblebee-SlackBuilds#16]
the link below seems not valid any more.

ftp://download.nvidia.com/XFree86/Linux-x86/$VERSION/NVIDIA-Linux-x86-$VERSION.run 
  ftp://download.nvidia.com/XFree86/nvidia-settings/nvidia-settings-$VERSION.tar.bz2 
  ftp://download.nvidia.com/XFree86/nvidia-xconfig/nvidia-xconfig-$VERSION.tar.bz2"

they have changed into 

http://download.nvidia.com/XFree86/Linux-x86/$VERSION/NVIDIA-Linux-x86-$VERSION.run 
http://download.nvidia.com/XFree86/nvidia-settings/nvidia-settings-$VERSION.tar.bz2 
http://download.nvidia.com/XFree86/nvidia-xconfig/nvidia-xconfig-$VERSION.tar.bz2"

**Comment by ryanpcmcquen** [comment]
Thanks, would you put together a PR?

**Comment by ryanpcmcquen** [comment]
Thanks for the PR!
