### ISSUE TITLE
 Lack of Legacy support

### ISSUE THREAD

**Issue by Incognito4nonymous** [WhiteWolf1776/Bumblebee-SlackBuilds#18]
Hi ! 

I recently decided to update my GPU's optimus Driver on my computer (Why...) And I noticed that the Legacy drivers which are the only ones that works with my machine, aren't actually supported by Bumblebee-SlackBuilds perhaps would it be possible to start a Legacy branch ? As far as I'm aware, the way of compiling the drivers completely changed from a version to another.

**Comment by ryanpcmcquen** [comment]
As far as I know, no one is maintaining this repo anymore. If you want to put together a pull request for a legacy branch I will merge it. Also, what do you mean by _legacy_?

**Comment by Incognito4nonymous** [comment]
Hum, 340.120, this : https://slackbuilds.org/repository/14.2/system/nvidia-legacy340-driver/
The support for the Nvidia drivers that are not longer maintained, lots of them has Optimus support.

**Comment by ryanpcmcquen** [comment]
If you want to put together a pull request for that, I will merge it.

**Comment by ryanpcmcquen** [comment]
It is worth noting that the `14.1` is on the `340.*` series.

**Comment by Incognito4nonymous** [comment]
I'll try to brew something from the 14.1 branch then, it worth a try and costs me nothing to do it after all.

**Comment by ryanpcmcquen** [comment]
Sounds good. Would you mind naming the branch `340.x`, or something like that? You may just want to maintain your own fork, and we can link to it in the README.

**Comment by Incognito4nonymous** [comment]
Okay, awesome, I named it Legacy for now, and will make something more concrete as soon as I'm back from my travel. ;)

**Comment by WhiteWolf1776** [comment]
terribly sorry to have let the repo go without updates for so long.  Work
has a way of taking your time... seemingly forever.

If this is still an issue, please let me know.

thanks

**Comment by Incognito4nonymous** [comment]
I seem to have duct taped the issue, to the point where I totally forgot about it.
