### ISSUE TITLE
[NVIDIA-Bumblebee] Add missing link for nvidia-modprobe archive in info file

### ISSUE THREAD

**Issue by arruor** [WhiteWolf1776/Bumblebee-SlackBuilds#19]
Add missing link in nvidia-bumblebee.info for nvidia-modprobe archive

**Comment by arruor** [comment]
Checked on Slackware 14.2 and -current. Now works as expected.
Keep doing such great work.
Thanks!

**Comment by ryanpcmcquen** [comment]
Thank _you_!
