### ISSUE TITLE
DOWNLOAD_x86_64 and checksum for nvidia-modprobe-390.12.tar.bz2 in nvidia-bumblebee.info is wrong

### ISSUE THREAD

**Issue by jisa0224** [WhiteWolf1776/Bumblebee-SlackBuilds#22]
Your is
`DOWNLOAD_x86_64="http://download.nvidia.com/XFree86/Linux_x86_64/$VERSION/NVIDIA-Linux-x86_64-$VERSION.run"`

but true url is
`DOWNLOAD_x86_64="http://download.nvidia.com/XFree86/Linux-x86_64/$VERSION/NVIDIA-Linux-x86_64-$VERSION.run"`

change "_x86_64" to "-x86_64" can download OK

also, the checksum ofnvidia-bumblebee/nvidia-modprobe-390.12.tar.bz2 is wrong
Your is
`5fe772b3f142978ef1dd06f83bff1a4`

But right one is
`85fe772b3f142978ef1dd06f83bff1a4`

miss the first digit

**Comment by ryanpcmcquen** [comment]
Pull request?

**Comment by jisa0224** [comment]
Pull request ok.

**Comment by ryanpcmcquen** [comment]
Closed via https://github.com/WhiteWolf1776/Bumblebee-SlackBuilds/pull/23.

Thank you for your contribution!
