### ISSUE TITLE
Update to 410.73 version of nVidia driver

### ISSUE THREAD

**Issue by KhazAkar** [WhiteWolf1776/Bumblebee-SlackBuilds#26]
nVidia released next long-live driver version from 4xx series in 25.10.2018, called 410.73. Can you update to that release of driver?

**Comment by ryanpcmcquen** [comment]
Would you mind sending in a PR for that?

**Comment by KhazAkar** [comment]
After testing my changes, sure :)

**Comment by ryanpcmcquen** [comment]
Closed via: https://github.com/WhiteWolf1776/Bumblebee-SlackBuilds/pull/27
