### ISSUE TITLE
Download script fix for nvidia-settings

### ISSUE THREAD

**Issue by lazyfox77** [WhiteWolf1776/Bumblebee-SlackBuilds#29]
Hello

The current download.sh script does not download nvidia-settings sources because does not parse the complete URL of nvidia-bumblebee.info file.

I just patch the script with this:

```
. $pkg/$pkg.info

  if [ "$ARCH" = "x86_64" ]; then
    case $pkg in
      nvidia-bumblebee)
        DOWNLOAD=$(echo $DOWNLOAD | cut -d ' ' -f1-)
        DOWNLOAD="$DOWNLOAD $DOWNLOAD_x86_64"

        MD5SUM=$(echo $MD5SUM | cut -d ' ' -f1-)
        MD5SUM="$MD5SUM $MD5SUM_x86_64"
        ;;
      *)
        DOWNLOAD=${DOWNLOAD_x86_64:-$DOWNLOAD}
        MD5SUM=${MD5SUM_x86_64:-$MD5SUM}
    esac
  fi

```

I just replace the `cut -d ' ' -f2-` by `cut -d ' ' -f1-` and  in my case, it's works.

Can you confirm this issue? I am using Slackware64-current on the test machine.

Thanks

**Comment by ryanpcmcquen** [comment]
Feel free to make a PR for this.

**Comment by nrj5k** [comment]
Looks good to me.

**Comment by ryanpcmcquen** [comment]
@WhiteWolf1776, let's hand over write access to whoever wants to take over this project.

**Comment by ryuuzaki42** [comment]
I think this can be close by: https://github.com/WhiteWolf1776/Bumblebee-SlackBuilds/commit/7af991088a8364b860dbd7028029d11a96d6e816#diff-110eb9dbeb64610712ac6a892115b8eea7aa11b010eee06475c15c72af32e1a3
