### ISSUE TITLE
optirun fails glxgears saying undefined symbol: _glapi_tls_Current

### ISSUE THREAD

**Issue by Francexi** [WhiteWolf1776/Bumblebee-SlackBuilds#30]
as per title, when running glx_gears (and any other application by far) i receive the following
```
francesco@darkstar:/usr/lib64$ optirun -v glxgears
[ 2634.437737] [INFO]Configured driver: nvidia
[ 2635.153372] [INFO]Response: Yes. X is active.
[ 2671.299568] [INFO]Running application using primus.
primus: fatal: failed to load any of the libraries: /usr/$LIB/libGL.so.1:/usr/lib/$LIB/libGL.so.1:/usr/$LIB/mesa/libGL.so.1:/usr/lib/$LIB/mesa/libGL.so.1
/usr/lib64/libGL.so.1: undefined symbol: _glapi_tls_Current
/usr/lib/$LIB/libGL.so.1: cannot open shared object file: No such file or directory
/usr/$LIB/mesa/libGL.so.1: cannot open shared object file: No such file or directory
/usr/lib/$LIB/mesa/libGL.so.1: cannot open shared object file: No such file or directory
```
any idea?

worth noting that:
```
francesco@darkstar:/usr/lib64$ readelf -Ws /usr/lib64/libGL.so | grep tls
    18: 0000000000000000     0 TLS     GLOBAL DEFAULT  UND _glapi_tls_Current
```

so the symbol is actually there

**Comment by ryanpcmcquen** [comment]
@Francexi, I'm not running this anymore, but we are looking for maintainers, maybe @lazyfox77 or @nrj5k have ideas on how to help here.

**Comment by nrj5k** [comment]
Hey, what version kernel and Nvidia driver are you using @Francexi

**Comment by Francexi** [comment]
hi, the version seems to be not critical, since the error appear with both 4.19 kernel + 410.66 driver and with 5.1 kernel + 418.74 driver (that I built from scratch after starting having this error in order to try to fix it)

**Comment by nrj5k** [comment]
Hmm, aight. I haven't had it which is why I wondered if it was version specific. Need to investigate further

**Comment by Francexi** [comment]
worth noting also that the symbol doesn't appear in any .so files provided by NVIDIA

**Comment by ryanpcmcquen** [comment]
@Francexi, have you tried `primusrun`?

**Comment by Francexi** [comment]
yes, same results. Anyway, talking with Patrick Volkerding, we discovered that libglvnd (recently added to -current) broke Bumblebee. Removing it and recompile solved the problem

**Comment by nrj5k** [comment]
I think it can be resolved by switching to the libglvnd version of the GLX client libs.

**Comment by Francexi** [comment]
i resolved editing primusrun, adding the line

`__GLVND_DISALLOW_PATCHING=1`

**Comment by ryanpcmcquen** [comment]
Interesting, if I were you I would add a wrapper for `primusrun` in `/usr/local/bin`.

**Comment by nrj5k** [comment]
@Francexi is that without removing Libglvnd and recompiling Mesa or with -current as is.

**Comment by ryanpcmcquen** [comment]
@Francexi, will you try again?
