### ISSUE TITLE
Primus-VK

### ISSUE THREAD

**Issue by nrj5k** [WhiteWolf1776/Bumblebee-SlackBuilds#35]
So the Vulkan API is getting increasingly common. Has anyone here tried [Primus-VK](https://github.com/felixdoerre/primus_vk)? 
And it would be nice to have it packaged along with Bumblebee here.

**Comment by ryanpcmcquen** [comment]
@nrj5k, do you want to take over this project and add Primus-VK support?

**Comment by nrj5k** [comment]
I don't have the time to figure out PrimusVK and getting it up and running right now and would like some help with that.
