### ISSUE TITLE
Slackware current changed name of xf86-video-nouveau-blacklist package

### ISSUE THREAD

**Issue by BradReed1** [WhiteWolf1776/Bumblebee-SlackBuilds#46]
From April 17th 2020 ChangeLog:
extra/xf86-video-nouveau-blacklist/xf86-video-nouveau-blacklist-1.0-noarch-1.txz: Added.
       If it is easier for people using slackpkg to leave xf86-video-nouveau
       installed and change the name of this package from xf86-video-nouveau to
       xf86-video-nouveau-blacklist with a $VERSION of 1.0, then so be it.
extra/xf86-video-nouveau-blacklist/xf86-video-nouveau-blacklist-noarch-1.txz: **Removed.**

The name change causes a minir issue with the build.

**Comment by BrunoLafleur** [comment]
I have corrected.
Thanks
