### ISSUE TITLE
ERROR Module glx does not have a glxModuleData data object.

### ISSUE THREAD

**Issue by ryuuzaki42** [WhiteWolf1776/Bumblebee-SlackBuilds#51]
Hello, firstly thanks for all the hard work.

In my notebook, Asus X510UR, with GeForce 930MX  in the Slackware Current:
![image](https://user-images.githubusercontent.com/11284038/92327221-7fb5bc80-f02e-11ea-8a40-ba2ad579c36b.png)

I got the error "[ERROR]Cannot access secondary GPU - error: [XORG] (EE) LoadModule: Module glx does not have a glxModuleData data object.".

I tried solve the problem with lot of ways, like change libglx.so in /usr/lib64/nvidia-bumblebee/xorg/modules/exteinsions ([bumblebee-working](https://www.linuxquestions.org/questions/slackware-14/has-anyone-got-bumblebee-working-with-kernel-4-19-2-a-4175642634/))

Tried a older Slackware kernel, tried a old version of nvidia-kernel with older Slackware Kernel, tried the last version (450.66) with the last kernel (5.4.62), also tried with new and clean install of Slackware Current and got the same error every time.

`$ optirun glxinfo | egrep "OpenGL vendor|OpenGL renderer"`
[  593.283111] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) LoadModule: Module glx does not have a glxModuleData data object.
[  593.283145] [ERROR]Aborting because fallback start is disabled.

`$ primusrun glxinfo | egrep "OpenGL vendor|OpenGL renderer"`
primus: fatal: Bumblebee daemon reported: error: [XORG] (EE) LoadModule: Module glx does not have a glxModuleData data object.

`# bumblebeed -vvv'`
...
[  999.057690] [INFO]Initialization completed - now handling client requests                                                                                                                                                                                                   
[ 1012.047817] [DEBUG]Accepted new connection
...
[ 1012.056751] [DEBUG][XORG] (II) Open ACPI successful (/var/run/acpid.socket)
[ 1012.056754] [DEBUG][XORG] (II) LoadModule: "glx"
[ 1012.056762] [DEBUG][XORG] (II) Loading /usr/lib64/nvidia-bumblebee/xorg/modules/extensions/libglx.so
[ 1012.056768] [ERROR][XORG] (EE) LoadModule: Module glx does not have a glxModuleData data object.
[ 1012.056773] [ERROR][XORG] (EE) Failed to load module "glx" (invalid module, 0)
[ 1012.056776] [DEBUG][XORG] (II) LoadModule: "nvidia"
...

The full log (https://pastebin.com/raw/GJxa6Ha9)

The version nvidia 450.66, has suport to 930MX (https://www.nvidia.com/download/driverResults.aspx/163238/en-us)

Looks like is about the /usr/lib64/nvidia-bumblebee/xorg/modules/extensions/libglx.so file, but any that I put there not working.

Thanks for any help

**Comment by ryuuzaki42** [comment]
Finally, is working : ). Comands that I used:

Go to the modules folder:
`cd /usr/lib64/nvidia-bumblebee/xorg/modules/`

Backup the old version of libGLX.so.0
`mv libGLX.so.0 libGLX.so.0`

Create a link simbolic from libglxserver_nvidia.XXX from the up folder
`ln ../libglxserver_nvidia.so.450.66 ./libGLX.so.0`

Now the error glx not appers, but the card is not dectected.
Need to set manualy the correctly card

See the card ID
`lspci | egrep 'VGA|3D'`

Uncomment the line with "BusID ..." and set the value in the last command.
I my case the value is "BusID "PCI:01:00:0"

`nano  /etc/bumblebee/xorg.conf.nvidia`

**Comment by BrunoLafleur** [comment]
The "card not detected" is the real error. The first one was not a blocking error. The driver can load glx with another path. That's why I don't see the error on my laptop.
I will submit a correction for the GLX error.

**Comment by ryuuzaki42** [comment]
Indeed @BrunoLafleur.

In the Slackware kernel update to 5.4.63, I tried just set the card in /etc/bumblebee/xorg.conf.nvidia and works.
So the part of set a new glx.so file was not need.
