### ISSUE TITLE
error while building the bumblebee package

### ISSUE THREAD

**Issue by swelac** [WhiteWolf1776/Bumblebee-SlackBuilds#62]
This is the output of make after the abort:

gcc -Wall -Waggregate-return 	-Wmissing-declarations -Wmissing-prototypes -Wredundant-decls 	-Wshadow -Wstrict-prototypes -Winline -Wformat=2 -pipe   -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Wextra -funsigned-char -DGITVERSION='"3.2.1-2013-04-26-Format:%h$"' -O2 -fPIC   -o bin/optirun src/module.o src/bbconfig.o src/bblogger.o src/bbrun.o src/bbsocket.o src/driver.o src/optirun.o src/bbsocketclient.o -lglib-2.0 -lrt 
/usr/bin/ld: src/bblogger.o:(.bss+0x220): multiple definition of `bb_pm_method_string'; src/bbconfig.o:(.data.rel.local+0x0): first defined here
/usr/bin/ld: src/bbsocket.o:(.bss+0x0): multiple definition of `bb_pm_method_string'; src/bbconfig.o:(.data.rel.local+0x0): first defined here
/usr/bin/ld: src/driver.o:(.bss+0x0): multiple definition of `bb_pm_method_string'; src/bbconfig.o:(.data.rel.local+0x0): first defined here
/usr/bin/ld: src/optirun.o:(.bss+0x0): multiple definition of `bb_pm_method_string'; src/bbconfig.o:(.data.rel.local+0x0): first defined here
/usr/bin/ld: src/bbsocketclient.o:(.bss+0x0): multiple definition of `bb_pm_method_string'; src/bbconfig.o:(.data.rel.local+0x0): first defined here
collect2: Error: ld returned 1 as end state
make: *** [Makefile:604: bin/optirun] error 1

**Comment by ryuuzaki42** [comment]
@swelac try now with #65
